program: main_infonce.py
data_dir: /scratch/data-registry/medical/openbhb
save_dir:  /scratch/output/brain-age-mri
model: resnet18
epochs: 50
batch_size: 32
lr: 1e-4
lr_decay: step
lr_decay_rate: 0.1
lr_decay_step: 10
optimizer: adam
momentum: 0.9
weight_decay: 1e-6
train_all: 1
method: expw
kernel: rbf
sigma: 1
trial: 0
tf: noise
noise_std: 1e-1
path: cluster
loss_choice: RnC
NN_nb_step_size: 0
end_NN_nb: 14
NN_nb_selection: manhattan
temp_RNC: 2
label_diff: l1
feature_sim: l2
lambda_val: 0
lambda_adv: 5e-6
grl_layer: 0
confound_loss: classification
lambda_mmd: 0
lambda_coral: 0
lambda_hsic: 0
modality: OpenBHB