program: main_infonce.py
data_dir: /scratch/data-registry/medical/openbhb
save_dir:  /scratch/output/brain-age-mri
model: resnet18
# change back to 300
epochs: 100
batch_size: 32
lr: 0.5
lr_decay: step
lr_decay_rate: 0.1
lr_decay_step: 10
optimizer: adam
momentum: 0.9
weight_decay: 1e-4
train_all: 1
method: expw
kernel: gaussian
sigma: 1
trial: 0
tf: none
path: local
loss_choice: RnC
NN_nb_step_size: 0
end_NN_nb: 14
NN_nb_selection: manhattan
temp_RNC: 2
label_diff: l1
feature_sim: l2