program: main_infonce.py
data_dir: /scratch/data-registry/medical/openbhb
save_dir:  /scratch/output/brain-age-mri
model: resnet18
# change back to 300
epochs: 50
batch_size: 32
lr: 1e-5
lr_decay: step
lr_decay_rate: 0.9
lr_decay_step: 10
optimizer: adam
momentum: 0.9
weight_decay: 1e-4
train_all: 1
method: expw
kernel: rbf
sigma: 2
trial: 0
tf: noise
noise_std: 1e-2
path: cluster
loss_choice: dynamic
NN_nb_step_size: 0
end_NN_nb: 14
NN_nb_selection: manhattan
temp_RNC: 2
label_diff: l1
feature_sim: l2
lambda_val: 0
lambda_adv: 0
grl_layer: 0
confound_loss: mmd
lambda_mmd: 1e-6
modality: MRE
